# Generated by Django 4.2.16 on 2025-01-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(help_text='Exemplo: COMUNICADO INTERNO Nº 033/2025/SEDUC', max_length=200)),
                ('recebido_de', models.CharField(help_text='Exemplo: Gabinete da Prefeita', max_length=100)),
                ('destino', models.CharField(help_text='Exemplo: Contabilidade', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada')], default='Pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios_protocolo/')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=10)),
                ('movimentacoes', models.ManyToManyField(related_name='relatorios', to='MGPROTOCOLO.movimentacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
