# Generated by Django 4.2.16 on 2025-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='fonte',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='recebido_de',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='status',
        ),
        migrations.RemoveField(
            model_name='relatorioprotocolo',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='relatorioprotocolo',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='relatorioprotocolo',
            name='movimentacoes',
        ),
        migrations.RemoveField(
            model_name='relatorioprotocolo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='relatorioprotocolo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='nome',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorioprotocolo',
            name='nome',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
