# Generated by Django 4.2.16 on 2025-01-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGPROTOCOLO', '0002_remove_movimentacao_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Memorando', 'Memorando'), ('Ofício', 'Ofício'), ('Relatório', 'Relatório'), ('Outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Criado', 'Criado'), ('Em Tramitação', 'Em Tramitação'), ('Concluído', 'Concluído')], default='Criado', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RelatorioProtocolo',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_recebidos', to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_criados', to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_recebidas', to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='MGPROTOCOLO.documento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_enviadas', to='MGPROTOCOLO.setor'),
        ),
    ]
