# Generated by Django 4.2.16 on 2025-01-28 18:59

import MGPROTOCOLO.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0003_documento_setor_delete_relatorioprotocolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=MGPROTOCOLO.models.diretorioDocumento),
        ),
    ]
