# Generated by Django 4.2.16 on 2025-01-28 19:31

import MGPROTOCOLO.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to=MGPROTOCOLO.models.diretorioProtocolo)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Finalizado', 'Finalizado')], default='Pendente', max_length=20)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_recebidos', to='MGPROTOCOLO.setor')),
                ('movimentacoes', models.ManyToManyField(related_name='protocolos', to='MGPROTOCOLO.movimentacao')),
            ],
        ),
    ]
