# Generated by Django 4.2.16 on 2025-01-29 19:20

import MGPROTOCOLO.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGPROTOCOLO', '0005_protocolomovimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='observacao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='data_movimentacao',
            new_name='realizado_em',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='descricao',
        ),
        migrations.AddField(
            model_name='documento',
            name='classificacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='comprovacao',
            field=models.FileField(blank=True, null=True, upload_to=MGPROTOCOLO.models.diretorioProtocolo),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='confirmacao',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('manual', 'Manual'), ('sistema', 'Sistema')], default='pendente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='setor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(blank=True, choices=[('em_tramitacao', 'Em tramitação'), ('recebida', 'Recebida')], default='em_tramitacao', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='setores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ProtocoloMovimentacao',
        ),
        migrations.AddField(
            model_name='processo',
            name='setor_demandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandante', to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='setor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandado', to='MGPROTOCOLO.setor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='MGPROTOCOLO.processo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='MGPROTOCOLO.processo'),
        ),
    ]
