# Generated by Django 4.2.16 on 2025-04-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_setor_usuarios'),
        ('MGPROTOCOLO', '0010_alter_movimentacao_status_alter_processo_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atual', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='demandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandante', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fim', to='HOME.setor'),
        ),
    ]
