# Generated by Django 4.2.16 on 2025-04-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_setor_usuarios'),
        ('MGPROTOCOLO', '0011_processo_atual_processo_demandante_processo_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='destinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SetorDestinatario', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SetorRemetente', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='protocolomovimentacao',
            name='destinatario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='SetoresDestinatarios', to='HOME.setor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processo',
            name='atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorAtual', to='HOME.setor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='demandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorDemandante', to='HOME.setor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorFim', to='HOME.setor'),
        ),
    ]
