# Generated by Django 4.2.16 on 2025-04-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0013_alter_protocolomovimentacao_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolomovimentacao',
            old_name='destinatario',
            new_name='destinataario',
        ),
    ]
