# Generated by Django 4.2.16 on 2025-04-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_setor_usuarios'),
        ('MGPROTOCOLO', '0014_rename_destinatario_protocolomovimentacao_destinataario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolomovimentacao',
            name='destinataario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='SetoresDestinatarios', to='HOME.setor'),
        ),
    ]
