# Generated by Django 4.2.16 on 2025-04-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0015_alter_protocolomovimentacao_destinataario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolomovimentacao',
            old_name='destinataario',
            new_name='destinatario',
        ),
    ]
