# Generated by Django 4.2.16 on 2025-04-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_setor_usuarios'),
        ('MGPROTOCOLO', '0017_remove_protocolomovimentacao_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolomovimentacao',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SetoresDestinatarios', to='HOME.setor'),
        ),
    ]
