# Generated by Django 4.2.16 on 2025-04-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0018_protocolomovimentacao_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='destinario',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='remetente',
        ),
    ]
