# Generated by Django 4.2.16 on 2025-04-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0021_alter_protocolomovimentacao_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolomovimentacao',
            name='destinatario',
        ),
    ]
