# Generated by Django 4.2.16 on 2025-04-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0023_protocolomovimentacao_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='destinario',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='remetente',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='atual',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='demandante',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='fim',
        ),
    ]
