# Generated by Django 4.2.16 on 2025-04-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_alter_setor_usuarios'),
        ('MGPROTOCOLO', '0024_remove_movimentacao_destinario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='destinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SetorDestinatario', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SetorRemetente', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorAtual', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='demandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorDemandante', to='HOME.setor'),
        ),
        migrations.AddField(
            model_name='processo',
            name='fim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SetorFim', to='HOME.setor'),
        ),
    ]
