# Generated by Django 4.2.16 on 2025-04-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0025_movimentacao_destinario_movimentacao_remetente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='destinario',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='remetente',
        ),
    ]
