# Generated by Django 4.2.16 on 2025-04-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0027_movimentacao_destinario_movimentacao_remetente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='destinario',
            new_name='destinatario',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='setor_destino',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='setor_origem',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='setor_atual',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='setor_demandante',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='setor_fim',
        ),
        migrations.RemoveField(
            model_name='protocolomovimentacao',
            name='setor_destino',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
