# Generated by Django 4.2.16 on 2025-04-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGPROTOCOLO', '0028_rename_destinario_movimentacao_destinatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('campo_alterado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField()),
                ('valor_novo', models.TextField()),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes', to='MGPROTOCOLO.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
