# Generated by Django 4.2.16 on 2025-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0029_correcaoprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcaoprocesso',
            name='campo_alterado',
            field=models.CharField(choices=[('numero', 'Número'), ('titulo', 'Título'), ('descricao', 'Descrição'), ('fim', 'Setor Fim')], max_length=50),
        ),
    ]
