# Generated by Django 4.2.16 on 2025-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0030_alter_correcaoprocesso_campo_alterado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('oficio', 'Ofício'), ('ci', 'Comunicado Interno'), ('despacho', 'Despacho'), ('memorando', 'Memorando'), ('parecer', 'Parecer'), ('laudo', 'Láudo'), ('relatorio', 'Relatório'), ('contrato', 'Contrato'), ('edital', 'Edital'), ('cotacoes', 'Cotações'), ('outros', 'Outros')], max_length=100, null=True),
        ),
    ]
