# Generated by Django 4.2.16 on 2025-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGPROTOCOLO', '0031_alter_documento_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], default='fisico', max_length=15),
        ),
    ]
