# Generated by Django 4.2.16 on 2025-06-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGPROTOCOLO', '0032_processo_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcaoprocesso',
            name='campo_alterado',
            field=models.CharField(choices=[('numero', 'Número'), ('titulo', 'Título'), ('descricao', 'Descrição'), ('fim', 'Setor Fim'), ('modalidade', 'Modalidade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('oficio', 'Ofício'), ('ci', 'Comunicado Interno'), ('despacho', 'Despacho'), ('memorando', 'Memorando'), ('parecer', 'Parecer'), ('portaria', 'Portaria'), ('laudo', 'Láudo'), ('relatorio', 'Relatório'), ('contrato', 'Contrato'), ('edital', 'Edital'), ('cotacoes', 'Cotações'), ('outros', 'Outros')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ComprovanteMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('movimentacoes', models.ManyToManyField(related_name='comprovantes', to='MGPROTOCOLO.movimentacao')),
            ],
        ),
    ]
