# Generated by Django 4.2.16 on 2025-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='condutor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fiscal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={},
        ),
        migrations.AddField(
            model_name='condutor',
            name='categoriaCNH',
            field=models.CharField(default='B', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condutor',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='condutor',
            name='cursoEscolar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condutor',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condutor',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desligado', 'Desligado')], default='Ativo', max_length=30),
        ),
        migrations.AddField(
            model_name='condutor',
            name='validadeCNH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='propriedade',
            field=models.CharField(choices=[('Próprio', 'Próprio'), ('Contratado', 'Contratado')], default='Administração', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('Em atividade', 'Em atividade'), ('Em manutenção', 'Em manutenção'), ('Excluído da frota', 'Excluído da frota')], default='Em atividade', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='km',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='quantidade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='valorTotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='valorUnitario',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='abastecimentos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='condutor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fiscal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table=None,
        ),
    ]
