# Generated by Django 4.2.16 on 2024-11-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abastecimentos',
            old_name='placa',
            new_name='veiculo',
        ),
    ]
