# Generated by Django 4.2.16 on 2025-01-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0002_alter_abastecimentos_options_alter_condutor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscal',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='categoriaCNH',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
