# Generated by Django 4.2.16 on 2024-11-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0002_rename_placa_abastecimentos_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimentos',
            options={'verbose_name': 'Abastecimentos', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AlterModelOptions(
            name='condutor',
            options={'verbose_name': 'Condutor', 'verbose_name_plural': 'Condutores'},
        ),
        migrations.AlterModelOptions(
            name='fiscal',
            options={'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterModelTable(
            name='abastecimentos',
            table='Abastecimentos',
        ),
        migrations.AlterModelTable(
            name='condutor',
            table='condutor',
        ),
        migrations.AlterModelTable(
            name='fiscal',
            table='fiscal',
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculo',
        ),
    ]
