# Generated by Django 4.2.16 on 2025-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0003_fiscal_cpf_alter_condutor_categoriacnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Negado', 'Negado')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='tipo',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel Comum', 'Diesel Comum'), ('Diesel S-10', 'Diesel S-10'), ('GNV', 'GNV'), ('Etanol', 'Etanol')], max_length=30),
        ),
    ]
