# Generated by Django 4.2.16 on 2025-01-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_secretaria'),
        ('MGCOMBUSTIVEIS', '0004_alter_abastecimentos_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.secretaria'),
        ),
    ]
