# Generated by Django 4.2.16 on 2025-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGCOMBUSTIVEIS', '0005_alter_veiculo_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='condutor',
            name='datanascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
