# Generated by Django 4.2.16 on 2024-12-02 15:22

import MGREGULARIDADEFISCAL.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='Certidao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FGTS', 'Certificado de Regularidade do FGTS - CRF'), ('FEDERAL', 'Certidão de Débitos Federais'), ('ESTADUAL', 'Certidão de Regularidade Fiscal Estadual'), ('CNDT', 'Certidão Negativa de Débitos Trabalhistas (CNDT)'), ('MUNICIPAL', 'Certidão de Regularidade Municipal')], max_length=15)),
                ('dataEmissao', models.DateField()),
                ('dataValidade', models.DateField()),
                ('autenticacao', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivo', models.FileField(upload_to=MGREGULARIDADEFISCAL.models.diretorioCertidao)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certidoes', to='MGC.fornecedores')),
            ],
            options={
                'unique_together': {('fornecedor', 'tipo', 'dataEmissao')},
            },
        ),
    ]
