# Generated by Django 4.2.16 on 2025-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGREGULARIDADEFISCAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao',
            name='validade',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
