# Generated by Django 4.2.16 on 2025-01-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGREGULARIDADEFISCAL', '0002_declaracao_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracao',
            name='validade',
        ),
    ]
