# Generated by Django 4.2.16 on 2025-06-07 18:37

import MGREGULARIDADEFISCAL.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGREGULARIDADEFISCAL', '0003_declaracao_arquivo_declaracao_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao',
            name='certidoes',
            field=models.ManyToManyField(related_name='declaracoes', to='MGREGULARIDADEFISCAL.certidao'),
        ),
        migrations.AddField(
            model_name='declaracao',
            name='emitido_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaracao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=MGREGULARIDADEFISCAL.models.diretorioDeclaracao),
        ),
    ]
