# Generated by Django 4.2.16 on 2025-06-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGREGULARIDADEFISCAL', '0004_declaracao_certidoes_declaracao_emitido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao',
            name='situacao',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='declaracao',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
