# Generated by Django 4.2.16 on 2025-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='link_modulo',
            field=models.CharField(max_length=100),
        ),
    ]
