# Generated by Django 4.2.16 on 2025-01-20 20:01

import HOME.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_alter_modulo_link_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='link_arquivo',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=HOME.models.diretorioTutorial),
        ),
    ]
