# Generated by Django 4.2.16 on 2025-02-28 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0004_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='secretaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
