# Generated by Django 4.2.16 on 2025-02-28 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0005_secretaria_ativo_secretaria_sigla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='secretaria_home', to=settings.AUTH_USER_MODEL),
        ),
    ]
