# Generated by Django 4.2.16 on 2025-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_alter_secretaria_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
