# Generated by Django 4.2.16 on 2025-04-13 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0009_alter_setor_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='HOME.secretaria'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='setor_home', to=settings.AUTH_USER_MODEL),
        ),
    ]
