# Generated by Django 4.2.16 on 2025-06-07 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0010_alter_setor_secretaria_alter_setor_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='secretario',
            field=models.ManyToManyField(related_name='secretaria_home', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setor',
            name='usuarios',
            field=models.ManyToManyField(related_name='setor_home', to=settings.AUTH_USER_MODEL),
        ),
    ]
