# Generated by Django 4.2.16 on 2025-02-26 18:06

import MGTRANSPARENCIA.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0004_secretaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data Limite')),
            ],
        ),
        migrations.CreateModel(
            name='DbDimensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DbCriterios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=6, unique=True, verbose_name='Código do Item')),
                ('criterio', models.TextField(verbose_name='Descrição do Critério')),
                ('periodicidade', models.CharField(choices=[('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Quadrimestral', 'Quadrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Tempestivo', 'Tempestivo')], max_length=20, null=True, verbose_name='Periodicidade')),
                ('classificacao', models.CharField(choices=[('Obrigatório', 'Obrigatório'), ('Essencial', 'Essencial'), ('Recomendado', 'Recomendado')], default='Obrigatório', max_length=20, verbose_name='Classificação')),
                ('dimensao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MGTRANSPARENCIA.dbdimensao', verbose_name='Dimensão')),
            ],
        ),
        migrations.CreateModel(
            name='DbAvaliacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=MGTRANSPARENCIA.models.diretorio_item_avaliacao, verbose_name='Anexo')),
                ('anotacao', models.TextField(blank=True, null=True, verbose_name='Anotação')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em análise', 'Em análise'), ('Publicado', 'Publicado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='MGTRANSPARENCIA.dbavaliacao', verbose_name='Avaliação')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='dbavaliacao',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGTRANSPARENCIA.dbcriterios', verbose_name='Critério Avaliado'),
        ),
        migrations.AddField(
            model_name='dbavaliacao',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='dbavaliacao',
            name='secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HOME.secretaria', verbose_name='Secretaria'),
        ),
    ]
