# Generated by Django 4.2.16 on 2025-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbavaliacao',
            name='data_limite',
        ),
        migrations.AddField(
            model_name='dbavaliacaolog',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.AddField(
            model_name='dbavaliacaolog',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='dbavaliacaolog',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='dbavaliacaolog',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Atrasado', 'Atrasado'), ('Em análise', 'Em análise'), ('Publicado', 'Publicado'), ('Publicado com atraso', 'Publicado com atraso')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
    ]
