# Generated by Django 4.2.16 on 2025-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0002_remove_dbavaliacao_data_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbavaliacao',
            name='status',
            field=models.CharField(choices=[('Atrasado', 'Atrasado'), ('Em dia', 'Em dia'), ('pendência', 'Com pendência')], default='Em dia', max_length=20, verbose_name='Status'),
        ),
    ]
