# Generated by Django 4.2.16 on 2025-02-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGTRANSPARENCIA', '0004_alter_dbcriterios_classificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbavaliacaolog',
            name='usuario',
        ),
        migrations.AddField(
            model_name='dbavaliacaolog',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Enviado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dbavaliacaolog',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Publicado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dbavaliacaolog',
            name='data_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite'),
        ),
        migrations.AlterField(
            model_name='dbavaliacaolog',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
    ]
