# Generated by Django 4.2.16 on 2025-02-28 02:02

import MGTRANSPARENCIA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0005_remove_dbavaliacaolog_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbavaliacaolog',
            name='arquivo',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=MGTRANSPARENCIA.models.diretorio_item_avaliacao, verbose_name='Anexo'),
        ),
    ]
