# Generated by Django 4.2.16 on 2025-02-28 14:25

import MGTRANSPARENCIA.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0006_alter_dbavaliacaolog_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('link', 'Links Úteis'), ('documento', 'Documento'), ('anotacao', 'Anotação')], max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('atual', 'Atual'), ('desatualizado', 'Desatualizado')], max_length=25, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('anotacao', models.TextField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to=MGTRANSPARENCIA.models.diretorio_manual_criterio)),
                ('geral', models.BooleanField(default=False)),
                ('criterio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MGTRANSPARENCIA.dbcriterios')),
            ],
        ),
    ]
