# Generated by Django 4.2.16 on 2025-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0007_informacoescriterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcriterios',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Quadrimestral', 'Quadrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Tempestivo', 'Tempestivo')], max_length=20, null=True, verbose_name='Periodicidade'),
        ),
    ]
