# Generated by Django 4.2.16 on 2025-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0009_rename_documentos_informacoescriterio_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcriterios',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Quadrimestral', 'Quadrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Tempestivo', 'Tempestivo')], max_length=20, null=True, verbose_name='Periodicidade'),
        ),
    ]
