# Generated by Django 4.2.16 on 2025-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTRANSPARENCIA', '0010_alter_dbcriterios_periodicidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbavaliacaolog',
            name='tarefa',
            field=models.TextField(blank=True, null=True, verbose_name='Tarefa'),
        ),
    ]
