# Generated by Django 4.2.16 on 2024-11-21 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoProcesso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade')),
                ('LinkEdital', models.URLField(blank=True, null=True, verbose_name='Edital')),
                ('LinkContrato', models.URLField(blank=True, null=True, verbose_name='Contrato')),
                ('Situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('SiglaUG', models.CharField(blank=True, max_length=10, null=True, verbose_name='UG')),
                ('Objeto', models.TextField(blank=True, null=True)),
                ('Valor', models.FloatField(blank=True, null=True)),
                ('UnidadeOrcamentaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade Orçamentária')),
                ('CodigoUG', models.CharField(blank=True, max_length=10, null=True)),
                ('PortariaComissaoLicitacao', models.CharField(blank=True, max_length=100, null=True)),
                ('NumeroProcesso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Processo')),
                ('UnidadeGestora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade Gestora')),
                ('CodigoContrato', models.CharField(blank=True, max_length=10, null=True)),
                ('AnoContrato', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('Vigencia', models.CharField(blank=True, max_length=100, null=True)),
                ('Estagio', models.CharField(blank=True, max_length=100, null=True)),
                ('CodigoPL', models.CharField(blank=True, max_length=10, null=True)),
                ('NumeroDocumento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('Municipio', models.CharField(blank=True, max_length=10, null=True)),
                ('TipoDocumento', models.CharField(blank=True, max_length=10, null=True)),
                ('NumeroContrato', models.CharField(blank=True, max_length=5, null=True, verbose_name='Contrato')),
                ('Esfera', models.CharField(blank=True, max_length=1, null=True)),
                ('AnoProcesso', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('AtualizarDados', models.BooleanField(default=True)),
                ('AtualizarItens', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDocumentoAjustado', models.CharField(blank=True, max_length=100, null=True)),
                ('RazaoSocial', models.CharField(blank=True, max_length=200, null=True)),
                ('CPF_CNPJ', models.CharField(blank=True, max_length=100, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=1000, null=True)),
                ('Representante', models.CharField(blank=True, max_length=200, null=True)),
                ('Contato', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Banco', models.CharField(blank=True, max_length=200, null=True)),
                ('Agencia', models.CharField(blank=True, max_length=200, null=True)),
                ('Conta', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('CodigoContratoOriginal', models.CharField(max_length=10)),
                ('Unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('PrecoUnitario', models.FloatField(blank=True, null=True)),
                ('CodigoItem', models.CharField(blank=True, max_length=10, null=True)),
                ('Quantidade', models.IntegerField(blank=True, null=True)),
                ('PrecoTotal', models.FloatField(blank=True, null=True)),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('dataehora', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoContrato', models.IntegerField(blank=True, null=True)),
                ('LinkArquivo', models.URLField(blank=True, null=True)),
                ('NumeroTermoAditivo', models.CharField(blank=True, max_length=20, null=True)),
                ('Vigencia', models.CharField(blank=True, max_length=200, null=True)),
                ('JustificativaTermoAditivo', models.TextField(blank=True, null=True)),
                ('ValorTermoAditivo', models.FloatField(blank=True, null=True)),
                ('AnoTermoAditivo', models.IntegerField(blank=True, null=True)),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoContratoSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(blank=True, default=0, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.contratos')),
                ('fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True)),
                ('dataehora', models.DateTimeField(auto_now=True)),
                ('totalporitem', models.FloatField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.contratos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.itens')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.ordem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordem',
            name='SaldoContratoSec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.saldocontratosec'),
        ),
        migrations.AddField(
            model_name='ordem',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EntradaSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True)),
                ('dataehora', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.contratos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.itens')),
                ('saldocontratosec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MGC.saldocontratosec')),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Secretaria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='Fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.fornecedores'),
        ),
    ]
