# Generated by Django 4.2.16 on 2024-10-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasec',
            name='saldocontratosec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MGC.saldocontratosec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saldocontratosec',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
