# Generated by Django 4.2.16 on 2024-11-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='PortariaComissaoLicitacao',
        ),
    ]
