# Generated by Django 4.2.16 on 2025-02-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_secretaria'),
        ('MGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldocontratosec',
            name='sec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.secretaria', verbose_name='Secretaria'),
        ),
    ]
