# Generated by Django 4.2.16 on 2024-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0002_entradasec_saldocontratosec_saldocontratosec_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidasec',
            name='totalporitem',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
