# Generated by Django 4.2.16 on 2025-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0002_alter_saldocontratosec_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='CodigoUG',
        ),
        migrations.AddField(
            model_name='contratos',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
