# Generated by Django 4.2.16 on 2024-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0002_remove_contratos_portariacomissaolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='AtualizarDados',
            field=models.TextField(default=True),
        ),
    ]
