# Generated by Django 4.2.16 on 2024-10-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0003_saidasec_totalporitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDocumentoAjustado', models.CharField(blank=True, max_length=100, null=True)),
                ('RazaoSocial', models.CharField(blank=True, max_length=200, null=True)),
                ('CPF_CNPJ', models.CharField(blank=True, max_length=100, null=True)),
                ('Endereco', models.CharField(blank=True, max_length=1000, null=True)),
                ('Representante', models.CharField(blank=True, max_length=200, null=True)),
                ('Contato', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='CPF_CNPJ',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='NumeroDocumentoAjustado',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='RazaoSocial',
        ),
        migrations.AddField(
            model_name='contratos',
            name='Fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MGC.fornecedores'),
            preserve_default=False,
        ),
    ]
