# Generated by Django 4.2.16 on 2025-03-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0003_remove_contratos_codigoug_contratos_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAditivoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroTermoAditivo', models.CharField(blank=True, max_length=20, null=True)),
                ('AnoTermoAditivo', models.IntegerField(blank=True, null=True)),
                ('ValorTermoAditivo', models.FloatField(blank=True, null=True)),
                ('LinkArquivo', models.URLField(blank=True, null=True)),
                ('JustificativaTermoAditivo', models.TextField(blank=True, null=True)),
                ('data_inicio', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='CodigoContrato',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='CodigoPL',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Esfera',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Municipio',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='NumeroDocumento',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='SiglaUG',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='TipoDocumento',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='UnidadeOrcamentaria',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Vigencia',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='CodigoContratoOriginal',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='CodigoItem',
        ),
        migrations.RemoveField(
            model_name='itens',
            name='PrecoTotal',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='Estagio',
            field=models.CharField(blank=True, choices=[('Execução', 'Em Execução'), ('Suspenso', 'Suspenso'), ('Fim da Vigência', 'Concluído - Fim da Vigência'), ('Anulado', 'Concluído - Anulado'), ('Rescindido', 'Concluído - Rescindido')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='UnidadeGestora',
            field=models.CharField(blank=True, choices=[('PMC', 'Prefeitura'), ('FMS', 'Saúde'), ('FMAS', 'Assistência'), ('FMEC', 'Educação'), ('CORTESPREV', 'CortêsPREV')], max_length=100, null=True, verbose_name='Unidade Gestora'),
        ),
        migrations.AlterField(
            model_name='saldocontratosec',
            name='saldoAtual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saldocontratosec',
            name='totalEntradas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='saldocontratosec',
            name='totalSaidas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='TermoAditivo',
        ),
        migrations.AddField(
            model_name='termoaditivovalor',
            name='Contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.contratos'),
        ),
    ]
