# Generated by Django 4.2.16 on 2024-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0003_alter_contratos_atualizardados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='AtualizarDados',
            field=models.BooleanField(default=True),
        ),
    ]
