# Generated by Django 4.2.16 on 2025-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0004_termoaditivovalor_remove_contratos_codigocontrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='Quantidade_disp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
