# Generated by Django 4.2.16 on 2024-10-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0004_fornecedores_remove_contratos_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoContrato', models.IntegerField(blank=True, null=True)),
                ('LinkArquivo', models.URLField(blank=True, null=True)),
                ('NumeroTermoAditivo', models.CharField(blank=True, max_length=20, null=True)),
                ('Vigencia', models.CharField(blank=True, max_length=200, null=True)),
                ('JustificativaTermoAditivo', models.TextField(blank=True, null=True)),
                ('ValorTermoAditivo', models.FloatField(blank=True, null=True)),
                ('AnoTermoAditivo', models.IntegerField(blank=True, null=True)),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MGC.contratos')),
            ],
        ),
    ]
