# Generated by Django 4.2.16 on 2024-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0004_alter_contratos_atualizardados'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldocontratosec',
            name='caixa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
