# Generated by Django 4.2.16 on 2025-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0005_itens_quantidade_disp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='AtualizarDados',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='AtualizarItens',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='Situacao',
        ),
        migrations.AlterField(
            model_name='ordem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
