# Generated by Django 4.2.16 on 2024-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0005_alter_ordem_arquivo_termoaditivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='Agencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='Banco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='Conta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
