# Generated by Django 4.2.16 on 2024-11-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0005_saldocontratosec_caixa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='SaldoContratoSec',
            new_name='saldoContratosec',
        ),
        migrations.RenameField(
            model_name='saldocontratosec',
            old_name='caixa',
            new_name='saldoAtual',
        ),
        migrations.RenameField(
            model_name='saldocontratosec',
            old_name='saldo',
            new_name='saldoInicial',
        ),
        migrations.RemoveField(
            model_name='entradasec',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='entradasec',
            name='sec',
        ),
        migrations.RemoveField(
            model_name='saidasec',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='saidasec',
            name='totalporitem',
        ),
        migrations.AddField(
            model_name='saidasec',
            name='saldocontratosec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MGC.saldocontratosec'),
            preserve_default=False,
        ),
    ]
