# Generated by Django 4.2.16 on 2024-11-30 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MGC', '0006_rename_saldocontratosec_ordem_saldocontratosec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidasec',
            name='saldocontratosec',
        ),
        migrations.AlterField(
            model_name='ordem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
