# Generated by Django 4.2.16 on 2024-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0006_fornecedores_agencia_fornecedores_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='AtualizarItens',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='AnoContrato',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='AnoProcesso',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='LinkContrato',
            field=models.URLField(blank=True, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='LinkEdital',
            field=models.URLField(blank=True, null=True, verbose_name='Edital'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='NumeroContrato',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='NumeroDocumento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='NumeroProcesso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='SiglaUG',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UG'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='TipoProcesso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='UnidadeGestora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade Gestora'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='UnidadeOrcamentaria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade Orçamentária'),
        ),
    ]
