# Generated by Django 4.2.16 on 2025-04-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0006_remove_contratos_atualizardados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidasec',
            name='saldocontratosec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MGC.saldocontratosec'),
        ),
    ]
