# Generated by Django 4.2.16 on 2024-11-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0007_remove_saidasec_saldocontratosec_alter_ordem_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldocontratosec',
            old_name='saldoInicial',
            new_name='totalEntradas',
        ),
        migrations.AddField(
            model_name='saldocontratosec',
            name='totalSaidas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entradasec',
            name='saldocontratosec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='MGC.saldocontratosec'),
        ),
    ]
