# Generated by Django 4.2.16 on 2024-10-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0007_contratos_atualizaritens_alter_contratos_anocontrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='Contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MGC.contratos'),
            preserve_default=False,
        ),
    ]
