# Generated by Django 4.2.16 on 2024-12-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0008_rename_saldoinicial_saldocontratosec_totalentradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='saldoContratosec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='MGC.saldocontratosec'),
        ),
    ]
