# Generated by Django 4.2.16 on 2024-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0008_itens_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='codigo',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
