# Generated by Django 4.2.16 on 2024-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0009_ordem_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordem',
            name='codigo',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
