# Generated by Django 4.2.16 on 2024-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGC', '0010_remove_ordem_id_alter_ordem_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordem',
            name='codigo',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
