# Generated by Django 4.2.16 on 2025-05-12 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0010_alter_setor_secretaria_alter_setor_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('documento_motivador', models.CharField(max_length=255)),
                ('prazo_geral', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('demanda', 'Demanda'), ('resposta', 'Resposta'), ('encaminhamento', 'Encaminhamento'), ('ciencia', 'Ciência')], default='demanda', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligencias', to='MGCOMUNICACAO.demanda')),
                ('setor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HOME.setor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDiligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diligencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='MGCOMUNICACAO.diligencia')),
            ],
        ),
    ]
